FROM maven:3.8-eclipse-temurin-17-alpine
WORKDIR /app
COPY pom.xml .
CMD ["./mvnw", "spring-boot:run", "-Dspring-boot.run.jvmArguments='-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005'"]